<#
.SYNOPSIS
    Creates a Desktop shortcut "PNUT M&M" that launches the desktop app.

.DESCRIPTION
    The shortcut points at "PNUT M&M.cmd" (console-less launcher), uses assets\icon.ico
    (generated by mnmparse.app.icon if it is missing) and runs with the project folder as
    its working directory.  Run it from any location:

        powershell -ExecutionPolicy Bypass -File make_shortcut.ps1

.PARAMETER Name
    Shortcut name (default "PNUT M&M").
#>
param(
    [string]$Name = "PNUT M&M"
)

$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $MyInvocation.MyCommand.Path
$launcher = Join-Path $root "PNUT M&M.cmd"
$icon = Join-Path $root "assets\icon.ico"
$python = Join-Path $root ".venv\Scripts\python.exe"

if (-not (Test-Path $launcher)) { throw "Launcher not found: $launcher" }
if (-not (Test-Path $icon)) {
    if (-not (Test-Path $python)) { throw "Cannot generate $icon - venv python not found at $python" }
    Write-Host "Generating $icon ..."
    & $python -m mnmparse.app.icon $icon
    if ($LASTEXITCODE -ne 0) { throw "Icon generation failed ($LASTEXITCODE)" }
}

$desktop = [Environment]::GetFolderPath("Desktop")
$linkPath = Join-Path $desktop "$Name.lnk"
$shell = New-Object -ComObject WScript.Shell
$shortcut = $shell.CreateShortcut($linkPath)
$shortcut.TargetPath = $launcher
$shortcut.WorkingDirectory = $root
$shortcut.IconLocation = "$icon,0"
$shortcut.Description = "PNUT M&M - Parses, Navigation, und Timers for Monsters and Memories"
$shortcut.WindowStyle = 7   # minimised: the .cmd window never shows; pythonw opens the app
$shortcut.Save()

Write-Host "Shortcut created: $linkPath"
